### ISSUE TITLE
Add a tag/release with a downloadable .exe

### ISSUE THREAD

**Issue by csuhta** [nt153133/D2RSaveFix#1]
Would you be able to create a GitHub release and upload a .exe file for people to download? I know how to compile the project with Visual Studio but a lot of other people just want to run the tool and will be a bit mystified by having to compile it first

Thanks for all the hard work!

**Comment by Xirious** [comment]
@nt153133 please do this. 

@csuhta is correct - some of us do not know how to compile it or do not want to.

**Comment by lciesielski** [comment]
@csuhta @Xirious if you are still in need of binaries you can check out my repo https://github.com/lciesielski/D2RSavePatcher it has binaries attached
Disclaimer: it is a comand-line tool instead of windows forms

**Comment by nt153133** [comment]
I generally don't like pre-compiled versions since it's bad security practice to trust a random exe but I uploaded one anyway in this case.
